from project_management import command_central
import time
import fileinput

command = command_central.CommandCentral()
command.create_new_project("/Users/Swgityswag/Desktop/test")
command.add_file("hello_world.c")
command.add_include("stdio.h")
command.add_func("main", "int", "definition")
time.sleep(1)
command.add_to_func_body("add", "call", value= "printf")
time.sleep(1)
command.add_to_func_body("modify", "add", value= "\"Hello world! %d\\n\"")
time.sleep(1)
command.add_to_func_body("add", "call", value= "printf")
time.sleep(1)
command.add_to_func_body("modify", "add", value= "\"testing!!\\n\"")
time.sleep(1)
command.add_to_func_body("add", "call", value= "printf")
time.sleep(1)
command.add_to_func_body("modify", "add", value= "\"One more\\n\"")
time.sleep(1)
command.add_to_func_body("modify", "add", line= 5, value= 6)
time.sleep(1)
command.add_to_func_body("add", "variable", value= "yes")
time.sleep(1)
command.add_to_func_body("modify", "type", value= "int")
time.sleep(1)
command.add_to_func_body("modify", "value", value= 10)
time.sleep(1)
command.add_to_func_body("add", "variable", value= "no")
time.sleep(1)
command.add_to_func_body("modify", "type", value="int")
command.add_to_func_body("add", "variable", value= "test")
time.sleep(1)
command.add_to_func_body("modify", "type", value="int")
command.add_to_func_body("modify", "value", value= 20)
command.add_to_func_body("add", "call", value="printf")
command.add_to_func_body("modify", "add", value= "\"one and one more\\n\"")